version: "3.9"

services:

  postgres:
    image: postgres:15.3-alpine
    networks:
      - backend_nw
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge
