version: "3.9"

services:
  frontend:
    # https://github.com/skypro-008/todo-list-frontend
    image: sermalenk/skypro-front:lesson-36
    ports:
      - 80:80
    restart: always
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/static/:/opt/static/
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./src/:/opt/todolist
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U ${POSTGRES_USER}", "-d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 5


networks:
  default:
    name: todolist_network

volumes:
  pg_data:
    name: todolist_pg_data
