# Generated by Django 4.2.2 on 2023-06-14 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.BigIntegerField(unique=True, verbose_name='Chat_ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('verification_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='Код доступа')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Телеграмм',
                'verbose_name_plural': 'Телеграммы',
            },
        ),
    ]
