version: "3.9"

services:
  frontend:
    image: sermalenk/skypro-front:lesson-38
    container_name: todolist_frontend
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/opt/static/
    depends_on:
      - api

  api:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:latest
    container_name: todolist_api
    env_file:
      - ./.env
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  tg_bot:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:latest
    container_name: todolist_tg_bot
    env_file:
      - ./.env
    restart: on-failure
    command: ./manage.py runbot
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.3-alpine
    container_name: todolist_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 10


networks:
  default:
    name: todolist_network

volumes:
  pg_data:
    name: todolist_pg_data
