version: "3.9"

services:
  frontend:
    # https://github.com/skypro-008/todo-list-frontend
    image: sermalenk/skypro-front:lesson-37
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/opt/static/
    depends_on:
      - api

  api:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:latest
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15.3-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 5


networks:
  default:
    name: todolist_network

volumes:
  pg_data:
    name: todolist_pg_data
