# Generated by Django 4.2.1 on 2023-06-13 07:30
from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Board = apps.get_model('goals', 'Board')
    BoardParticipant = apps.get_model('goals', 'BoardParticipant')
    GoalCategory = apps.get_model('goals', 'GoalCategory')

    with transaction.atomic():
        now_time = timezone.now()
        # for user_id in User.objects.values_list('id', flat=True)
        for user in User.objects.all():
            new_board = Board.objects.create(
                title='Moи цели',
                created=now_time,
                updated=now_time
            )
            BoardParticipant.objects.create(
                user=user,
                board=new_board,
                role=1,
                created=now_time,
                updated=now_time
            )
            GoalCategory.objects.filter(user=user).update(board=new_board)


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0004_board_goalcategory_board_boardparticipant'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
